on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    - name: 'Run Azure image builder'
      uses: azure/imageBuildery@v0
      with: 
        ResourceGroupName: distributorRG
        imageType: PlatformImage
        imagebuilderTemplateName: ubuntu1804 
        buildTimeoutInMinutes: 80 
        source: 
          - offer:
          - publisher:
          - sku:
          - os-type: 
        #####List of Customizer values, comma separated#########
        customizer:
          [
            [
            - type: shell
            - name: runCustomScript
            - source: https://raw.githubusercontent.com/lnochili/learn-git/master/aib-shellscript.sh
            - destination: /tmp/aib-hostnameScript.sh
            ],
            [
            - type: shell-inline
            - name: setupBuildPath
            - source:
                sudo mkdir /buildArtifacts
                sudo cp /tmp/index.html /buildArtifacts/index.html
            - destination: /tmp/aib-hostnameScript.sh
            ]
          ]
        ########Distributor details #############
        distributor:
          - type: ManagedImage
          - imagedef: /subscriptions/<Subscription-ID>/resourceGroups/<GalleryRG>/providers/Microsoft.Compute/images/<imageDefName>
          - location: "West US2"
          - runOutputName: imageDefName.${BuildID}  #### this ID needs to be Unique
          - artifactTags: "UbuntuServer 18.04LTS"
