on: 
  push
jobs:
  create-run-ibtemplate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master

      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'create and run Azure image builder'
        uses: azure/imageBuilder@v0
      - inputs: 
          resource-group-name:  #mandatory
             description: 'Azure Resource Group to create IB Template'
             required: string
             default: null 
          image-type: #optional [ManagedImage | GalleryImage | PlatformImage]
            description: 'Source image type' 
            required: string
            default: 'PlatformImage'
          build-timeout-in-minutes: #Optional
            description: 'Image builder timeout'
            required: integer
            default: 80
          imagebuilder-template-name:  #optional
            description: 'Template resource name'
            required: string
            default: [generated-unique-string based on rg name and imagetype]
          source-os-type: #mandatory
            description: 'Source OS type'
            required: string
            default: 'linux' 
          source-image: #mandatory in format : { publisher:offer:sku:version }; Example:  {Ubuntu:Canonical:18.04-LTS:latest } 
            description: 'Source Image details" '
            required: string  
          #####List of Customizer values, comma separated#########
          customizer-type: #optional [ShellScriptPath | InlineScript | File]
            description: 'Customizer type ShellScriptPath | InlineScript | File'
            required: string
            default: "File"
          customizer-name: #optional only if customizer type is declared
            description: 'Customizer name'
            required: string
            default: [Generate a name based on workflow name]
          customizer-source: #optional only if customizer type is declared
            description: 'customizer source URI/path/multiline cmds'
            required: string
            default: [folder path of github artifacts]
          customizer-destination: #optional
            description: 'customizer destination for File type customizer'
            required: string
            default: [a working directory in VM]
          ########Distributor details #############
          distributor-type: #optional
            description: 'Distributor type ManagedImage or Shared Image gallery'
            required: string  #[ManagedImage|SharedImage]
            default: ManagedImage
          managed-image-resourcegroup: #mandatory if distributor type is ManagedImage'
            description: 'Resource group for creating managed image'
            required: string #
            default: $resource-group-name   #same as template resource group
          sig-image-definition: #mandatory if distributor type is shared image'
            description: 'Resource ID of image definition in shared image gallery: /subscriptions/<Subscription-ID>/resourceGroups/<GalleryRG>/providers/Microsoft.Compute/images/<imageDefName>'
            required: string 
          sig-location: #mandatory if distributor type is shared image'
            description: ' location of image definition  '
            required: string
            default:  #same as Image Gallery Resource Group 
          sig-runoutput-name: #optional
            description: 'To query image template run status to get shared image version details'
            required: string
            default: $sig-image-definition.$GITHUB_RUNNUMBER  #### this ID needs to be Unique
          sig-artifactTags: #optional 
            description: 'Tags for images in Gallery or managed or VHD '
            required: string
            default: $imagebuilder-template-name; $source-os-type'
        - outputs:
            ## the outputs of the Image Builder run can be used by the subsequent action 
            image-builder-run-status: #mandatory
              description: 'Status of image builder template run status'
              required: string   # Values of Provisioning: "Succeeded" or "Failed"
            run-output-name: #mandatory and will be emitted when template run was successful
              description: 'image template run id to query in subsequent actions'
              required: string
             vhd-uri: #If the distributor is a VHD, the artifact URI will have the URI to the image which includes Azure storage account
              description: 'vhd image uri for subsequent actions'
              required: string
