# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
# Azure Image Builder work flow using Azure CLI

name: Share data between jobs

on: [push]

jobs:
  job_1: 
    name: Azure Image builder run 
    runs-on: ubuntu-latest
    env:
      image_template_name: "UbuntuServer18.04LTS"
      run_output_name: ${{jobs.job_1.env.version}}
      ######Source image details########### 
      type: "PlatformImage"
      publisher: "Canonical"
      offer": "UbuntuServer"
      sku: "18.04-LTS"
      version: "latest"    
     ######Target Distribution details###########
      distributor_resource_group: "iblinuxGalleryRG"
      image_gallery_name: "iblinuxGallery"
      image_definition: "iblinux"
      image_version: "0.1"
      image_location: "West US2"
    ########Custom Scipt location#######
    
    steps:  
        - name: 'Checkout Github Action' 
          uses: actions/checkout@master

        - name: azure authentication
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDS }}
             
        - name: azure Image builder prerequisites 
          uses: azure/cli@v1
          with:
              creds: ${{secrets.AZURE_CREDS}}  
            ######Source image details########### 
              type: "PlatformImage"
              publisher: "Canonical"
              offer": "UbuntuServer"
              sku: "18.04-LTS"
              version: "latest"    
              os_type: "Linux"
              inlineScript: |
                az role assignment create --assignee cf32a0cc-373c-47c9-9156-0db11f6a6dfc --role Contributor \
                    --scope /subscriptions/{{secrets.AZURE_CREDS.subscriptionID}}/resourceGroups/${{env.distributorResourceGroup}}
                az group create -n ${{env.distributor_resource_group}} -l ${{env.image_location}}
                az sig create -g ${distributor_resource_group}  --gallery-name ${image_gallery_name}
                az sig image-definition create -g ${{env.distributor_resource_group}} --gallery-name ${{env.image_gallery_name}} \
                  --gallery-image-definition ${{env.image_definiation}} --publisher ${{publisher}} --offer ${{offer}}  \
                      --sku ${{sku}}  --os-type ${{os_type}}
                         
        - name: 'Update AIB standard template with inputs'
          run: |
            mkdir $GITHUB_WORKSPACE/aib-local
            curl https://raw.githubusercontent.com/raiyanalam/azureImageBuilderAction/master/PlatformImageTemplate-UbuntuLinuxCanonical.json -o ./aiblocal/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<subscriptionID>/${{secrets.AZURE_CREDS.subscriptionID}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<rgName>/${{env.distributor_resource_group}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<region>/${{env.image_location}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<imageName>/${{env.image_definition}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<runOutputName>/${{env.run_output_name}}/g" $GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json
            
        #### Azure Image builder actions ####              
        - name: Create azure Image builder template   
          uses: azure/cli@v1
          with:
            creds: ${{secrets.AZURE_CREDS}}                          
            inlineScript: |
              ###Create Image Template Resource###
                az resource create  --resource-group ${{env.distributor_resource_group}}  \ 
                    --properties @$GITHUB_WORKSPACE/aib-local/PlatformImageTemplate-UbuntuLinuxCanonical.json \
                      --is-full-object  --resource-type Microsoft.VirtualMachineImages/imageTemplates -n ${{env.image_template_name}}
        - name: Add Customizers to azure Image builder template
          uses: azure/cli@v1
          with:
            creds: ${{secrets.AZURE_CREDS}}   
            customizer.type: "shell"
            customizer.name: "RunScriptFromSource"
            customizer.scriptUri: "https://raw.githubusercontent.com/raiyanalam/azureImageBuilderAction/master/PlatformImageTemplate-UbuntuLinuxCanonical.json"
            inlineScript: |
              ###Update Image template with customizers###
              az image builder  customizer add --resource-group ${{env.distributor_resource_group}} -n ${{env.image_template_name}} \ 
                    --scripts $customizer.scriptUri  --customizer-name $customizer.name --type $customiser.type 
                    
              az image builder  customizer add --resource-group ${{env.distributor_resource_group}} -n ${{env.image_template_name}} \ 
                    --inline-script "sudo mkdir /buildArtifacts" \"sudo cp /tmp/index.html /buildArtifacts/index.html" \
                      --customizer-name shell-script-inline  
        - name: Run azure Image builder template
          uses: azure/cli@v1
          with:   
            creds: ${{secrets.AZURE_CREDS}}                       
            inlineScript: |
              #### Run Image Template Resource ###
                az resource invoke-action  --resource-group ${{env.distributor_resource_group}}  \
                      --resource-type  Microsoft.VirtualMachineImages/imageTemplates -n ${{env.image_template_name}} --action Run
