# https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
# Azure Image Builder work flow using Azure CLI

name: Share data between jobs

on:
  [push]

jobs:
  job_1:
    name: Azure Image builder run 
    runs-on: ubuntu-latest
    env:
      image_template_name: "UbuntuServer18.04LTS"
      run_output_name: $GITHUB_RUN_NUMBER
      type: "PlatformImage"
      distributor_resource_group: "iblinuxGalleryRG"
      image_gallery_name: "iblinuxGallery"
      image_definition: "iblinux"
      image_version: "0.1"
      image_location: "westus2"
      publisher: "Canonical"
      offer: "UbuntuServer"
      sku: "18.04-LTS"
      version: "latest"    
      os_type: "Linux"
      customizer.type: "shell"
      customizer.name: "RunScriptFromSource"
      customizer.scriptUri: "https://raw.githubusercontent.com/lnochili/azure-actions-imagebuilder/master/.github/workflows/customizerscript.sh"

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
      
      - name: azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: azure Image builder prerequisites
        uses: azure/CLI@v1
        with:
          inlineScript: |
            mkdir $GITHUB_WORKSPACE/aib_local
            az account show --query id > $GITHUB_WORKSPACE/aib_local/subscriptionId.out
            az group create -n ${{ env.distributor_resource_group }} -l ${{ env.image_location }} 
            az sig create -g ${{ env.distributor_resource_group }}  --gallery-name ${{ env.image_gallery_name }} 
            az sig image-definition create -g ${{ env.distributor_resource_group }} --gallery-name ${{ env.image_gallery_name }} --gallery-image-definition ${{ env.image_definition }} --publisher ${{ env.publisher }} --offer ${{ env.offer }} --sku ${{ env.sku }} --os-type ${{env.os_type }} 
            cat $GITHUB_WORKSPACE/aib_local/subscriptionId.out
      - name: Create azure Image builder template   
        uses: azure/cli@v1
        with:
          inlineScript: | 
            subscriptionId=`cat $GITHUB_WORKSPACE/aib_local/subscriptionId.out`
            rgName=${{ env.distributor_resource_group }}
            imgLocation=${{ env.image_location }}
            imgDefinition=${{ env.image_definition }}
            runOutputName=${{ env.run_output_name }}
            userTags= [ ${{ env.version }},${{ env.run_output_name }} ]
            curl https://raw.githubusercontent.com/lnochili/azure-actions-imagebuilder/master/PlatformImageTemplate-UbuntuLinuxCanonical.json -o ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<subscriptionID>/$subscriptionId/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<region>/$imgLocation/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<ImageDefName>/$imgDefinition/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<runOutputName>/$runOutputName/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<resourceGroupID>/$rgName/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            sed -i -e "s/<artifactTags>/$userTags/g" ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            cat ./PlatformImageTemplate-UbuntuLinuxCanonical.json
            az resource create --resource-group ${{ env.distributor_resource_group }} --properties @./PlatformImageTemplate-UbuntuLinuxCanonical.json --is-full-object  --resource-type Microsoft.VirtualMachineImages/imageTemplates -n ${{ env.image_template_name }}
      
      - name: Add Customizers to azure Image builder template
        uses: azure/cli@v1
        with:
          inlineScript: |
            az image builder  customizer add --resource-group ${{ env.distributor_resource_group }} -n ${{ env.image_template_name }} --scripts ${{ env.customizer.scriptUri }}  --customizer-name ${{ env.customizer.name}} --type ${{ env.customiser.type }}
            az image builder  customizer add --resource-group ${{ env.distributor_resource_group }} -n ${{ env.image_template_name }} --inline-script "sudo mkdir /buildArtifacts" \"sudo cp /tmp/index.html /buildArtifacts/index.html" --customizer-name shell-script-inline  
      - name: Run azure Image builder template
        uses: azure/cli@v1
        with:   
          creds: ${{ secrets.AZURE_CREDENTIALS }}                       
          inlineScript: |
            #### Run Image Template Resource ###
            az resource invoke-action  --resource-group ${{ env.distributor_resource_group }} --resource-type  Microsoft.VirtualMachineImages/imageTemplates -n ${{ env.image_template_name }} --action Run
